version: '3'

services:
  web:
    image: registry.gitlab.com/your-username/nginx-customized
    ports:
      - 80:80

  db:
    image: registry.gitlab.com/your-username/postgres-customized
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
